### ISSUE TITLE
404 not found error

### ISSUE THREAD

**Issue by lawpdas** [zju3dv/OnePose#1]
Thanks for your great work!
I want to know more details about the pose refinement. But there is a 404 not found error on the project page, the supplementary material cannot be downloaded. Could you fix this error?

**Comment by JiamingSuen** [comment]
Thanks for the heads up. The link is fixed and you can download it [here](https://zju3dv.github.io/onepose/files/onepose_supp.pdf).

**Comment by HannahHaensen** [comment]
is there already a release date planned for the code?
