### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by jylammp** [zju3dv/OnePose#12]
When I am running this command:

python run.py +preprocess=sfm_spp_spg_val.yaml

then    show   the error "Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace."
how to  solve  it?

**Comment by DeriZSY** [comment]
This means you need to set the variable HYDRA_FULL_ERROR=1 to enable a full stack trace for the error.
More error information is needed for us to solve your problem.
