### ISSUE TITLE
refine ARKit pose

### ISSUE THREAD

**Issue by lawpdas** [zju3dv/OnePose#2]
I am trying to refine the ARKit pose with COLMAP. I first use `point_triangulator` to reconstruct from the ARKit poses, then I use `bundle_adjuster` for refinement. But the results are bad.
I noticed that you use COLMAP in this work. How to use it for pose refinement? Could you give me some help?

**Comment by JiamingSuen** [comment]
We did exactly what you described above and the results are good.

**Comment by lawpdas** [comment]
Thanks! 
In bundle adjust, I saw a very large BA cost (e.g., 2.648562e+06) which makes the convergence difficult. I think it was caused by the inaccurate ARKit pose. What APP is used for data collection in this work? ios_logger? Could you also release the script for pose refinement?

**Comment by JiamingSuen** [comment]
We use a custom-built app to capture all the data. Sorry that we can't release the app or the data processing code due to the company policy. ARKit poses from ios_logger should be good enough for BA in COLMAP.
