### ISSUE TITLE
Demo on Huggingface

### ISSUE THREAD

**Issue by MohamedAliRashad** [zju3dv/OnePose#20]
Can a demo using Gradio on Huggingface be made?
It will be very nice if anyone was able to try your work.

**Comment by DeriZSY** [comment]
> Can a demo using Gradio on Huggingface be made? It will be very nice if anyone was able to try your work.

Hi, thanks for your interest in the work! Yeah, the demo part and application release have always been in our plan. However, the main authors (including me) have shifted the focus from academia to running a start-up project and have been crazily busy in the past year. Please stay tuned for the release of the demo and the application for data annotation.
