### ISSUE TITLE
tracking pipeline

### ISSUE THREAD

**Issue by ghoshaw** [zju3dv/OnePose#26]
Thank you for the great work and the code release.
Is there any estimated date for the Demo release, because I am really curious how the code will run on a custom made dataset.

Thanks in advance!

**Comment by siatheindochinese** [comment]
You can check out the realtime inference I attempted on a coconut carton here: https://www.linkedin.com/posts/sia-zhen-hao_opencv-computervision-machinelearning-activity-6965918457116733440-IAXE

The images and labels used to generate the SfM point cloud are generated synthetically after 3D-scanning the object (the authors have yet to release the OnePose Cap app for collecting real data, so synthetic data will have to do for now).

**Comment by ghoshaw** [comment]
> 

ok, thanks
