### ISSUE TITLE
How to get the real size of object in colmap reconstruction?

### ISSUE THREAD

**Issue by ghoshaw** [zju3dv/OnePose#27]
As above, you record the data using ARKIT and saved pose of ARKIT, but only use the pose to select covis pairs, then how to get the real size of the obj?

**Comment by DeriZSY** [comment]
> As above, you record the data using ARKIT and saved pose of ARKIT, but only use the pose to select covis pairs, then how to get the real size of the obj?

Thanks for your interest in our work, this is a good question. We apply SfM in a two-stage manner. We first apply triangulation with ARKit poses and then run bundle adjustment on the reconstructed point clouds and ARKit poses. In this way, the true scale of the object can be maximally preserved. 
You're welcome to re-open the issue if this doesn't solve your questions.
