### ISSUE TITLE
how's the speed of one pose?

### ISSUE THREAD

**Issue by lucasjinreal** [zju3dv/OnePose#3]
can u runs in realtime with CPU?

BTW, any timeline on when open source the code?

**Comment by Utopiah** [comment]
"OnePose achieves better precision without training for any object instances or categories in the validation set, while taking only _58 ms_ to process one frame on GPU." p2

**Comment by lucasjinreal** [comment]
Does there any specific model of **this** GPU?

**Comment by Utopiah** [comment]
"All the experiments are conducted on an NVIDIA TITAN RTX GPU." p7

**Comment by lucasjinreal** [comment]
oh, I see.
