### ISSUE TITLE
text file is missing

### ISSUE THREAD

**Issue by Azad99** [zju3dv/OnePose#33]
hi, 
I am on the 2nd step of (Inference on OnePose dataset), and after running this command (python inference.py +experiment=test_GATsSPG.yaml object_detect_mode=feature_matching save_wis3d=False
), it gives the following error at 46th object.

OSError: /home/nstu/Downloads/OnePose-main/data/onepose_datasets/test_data/0519-backpack1-box/backpack1-4/poses_ba/754.txt not found.

**Comment by cttxy** [comment]
Hello, I am getting the error "OSError: /root/data1/OnePose/data/onepose_datasets/test_data/0519-backpack1-box/backpack1-4/poses_ba/745.txt not found.", similar to the one you are getting. similar to what you are experiencing.
How did you solve this problem?
