### ISSUE TITLE
Solving conda env gets stuck (~/OnePose$ conda env create -f environment.yaml

### ISSUE THREAD

**Issue by monajalal** [zju3dv/OnePose#38]
How long do you expect the following command to take?
I am not sure if it is stuck or would just really take a long while?
![Screenshot from 2023-02-15 09-25-37](https://user-images.githubusercontent.com/1892917/219055555-8bbfcc04-be85-419b-b59b-0126682c6ea1.png)

![image](https://user-images.githubusercontent.com/1892917/219055505-78ef7e5f-5746-447d-8d12-d0c82856808a.png)

**Comment by fff128170** [comment]
@monajalal I also encountered this problem, did you solve it?

**Comment by GuillaumeGrimard** [comment]
same thing here

**Comment by luffy-yu** [comment]
I met the same issue. I was trying to set up the environment on Windows. It prompted some version conflicts. Therefore, I removed some versions, and then it can install.
FYI

- `environment.yml`
```
name: onepose
channels:
  # - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.8
  - torchvision=0.9
  - cudatoolkit=10.2
  - ipython
  - tqdm
  - matplotlib
  - pylint
  - conda-forge::jupyterlab
  - conda-forge::h5py
  - conda-forge::loguru
  - conda-forge::scipy
  - conda-forge::numba
  - conda-forge::ipdb
  - conda-forge::albumentations
  - pip
  - pip:
    - -r requirements.txt
```

- `requirements.txt`
```
pytorch-lightning==1.5
aiohttp
aioredis
pydegensac
opencv_python==4.4.0.46
yacs>=0.1.8
einops
kornia
pickle5
timm>=0.3.2
hydra-core
omegaconf
pycocotools
wandb
rich
transforms3d
natsort
```

**Comment by luffy-yu** [comment]
Actually, you may get this error `AssertionError: Torch not compiled with CUDA enabled` after creating the conda env.

uninstall `torch torchvision torchaudio` first, and install them via

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116`

**Comment by EvdoTheo** [comment]
> I met the same issue. I was trying to set up the environment on Windows. It prompted some version conflicts. Therefore, I removed some versions, and then it can install. FYI
> 
> * `environment.yml`
> 
> ```
> name: onepose
> channels:
>   # - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
>   - pytorch
>   - conda-forge
>   - defaults
> dependencies:
>   - python=3.7
>   - pytorch=1.8
>   - torchvision=0.9
>   - cudatoolkit=10.2
>   - ipython
>   - tqdm
>   - matplotlib
>   - pylint
>   - conda-forge::jupyterlab
>   - conda-forge::h5py
>   - conda-forge::loguru
>   - conda-forge::scipy
>   - conda-forge::numba
>   - conda-forge::ipdb
>   - conda-forge::albumentations
>   - pip
>   - pip:
>     - -r requirements.txt
> ```
> 
> * `requirements.txt`
> 
> ```
> pytorch-lightning==1.5
> aiohttp
> aioredis
> pydegensac
> opencv_python==4.4.0.46
> yacs>=0.1.8
> einops
> kornia
> pickle5
> timm>=0.3.2
> hydra-core
> omegaconf
> pycocotools
> wandb
> rich
> transforms3d
> natsort
> ```

Nothing changed for me. I keep having the same issue.

**Comment by luffy-yu** [comment]
> > I met the same issue. I was trying to set up the environment on Windows. It prompted some version conflicts. Therefore, I removed some versions, and then it can install. FYI
> > 
> > * `environment.yml`
> > 
> > ```
> > name: onepose
> > channels:
> >   # - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
> >   - pytorch
> >   - conda-forge
> >   - defaults
> > dependencies:
> >   - python=3.7
> >   - pytorch=1.8
> >   - torchvision=0.9
> >   - cudatoolkit=10.2
> >   - ipython
> >   - tqdm
> >   - matplotlib
> >   - pylint
> >   - conda-forge::jupyterlab
> >   - conda-forge::h5py
> >   - conda-forge::loguru
> >   - conda-forge::scipy
> >   - conda-forge::numba
> >   - conda-forge::ipdb
> >   - conda-forge::albumentations
> >   - pip
> >   - pip:
> >     - -r requirements.txt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * `requirements.txt`
> > 
> > ```
> > pytorch-lightning==1.5
> > aiohttp
> > aioredis
> > pydegensac
> > opencv_python==4.4.0.46
> > yacs>=0.1.8
> > einops
> > kornia
> > pickle5
> > timm>=0.3.2
> > hydra-core
> > omegaconf
> > pycocotools
> > wandb
> > rich
> > transforms3d
> > natsort
> > ```
> 
> Nothing changed for me. I keep having the same issue.

Which OS do you use? My reply was based on Win 11.

**Comment by EvdoTheo** [comment]
> > > I met the same issue. I was trying to set up the environment on Windows. It prompted some version conflicts. Therefore, I removed some versions, and then it can install. FYI
> > > 
> > > * `environment.yml`
> > > 
> > > ```
> > > name: onepose
> > > channels:
> > >   # - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
> > >   - pytorch
> > >   - conda-forge
> > >   - defaults
> > > dependencies:
> > >   - python=3.7
> > >   - pytorch=1.8
> > >   - torchvision=0.9
> > >   - cudatoolkit=10.2
> > >   - ipython
> > >   - tqdm
> > >   - matplotlib
> > >   - pylint
> > >   - conda-forge::jupyterlab
> > >   - conda-forge::h5py
> > >   - conda-forge::loguru
> > >   - conda-forge::scipy
> > >   - conda-forge::numba
> > >   - conda-forge::ipdb
> > >   - conda-forge::albumentations
> > >   - pip
> > >   - pip:
> > >     - -r requirements.txt
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > * `requirements.txt`
> > > 
> > > ```
> > > pytorch-lightning==1.5
> > > aiohttp
> > > aioredis
> > > pydegensac
> > > opencv_python==4.4.0.46
> > > yacs>=0.1.8
> > > einops
> > > kornia
> > > pickle5
> > > timm>=0.3.2
> > > hydra-core
> > > omegaconf
> > > pycocotools
> > > wandb
> > > rich
> > > transforms3d
> > > natsort
> > > ```
> > 
> > 
> > Nothing changed for me. I keep having the same issue.
> 
> Which OS do you use? My reply was based on Win 11.

I use Ubuntu 20.04. I omitted the requirements.txt file completely and I tried to install all the libraries manually. For now, it is working.
