### ISSUE TITLE
trial

### ISSUE THREAD

**Issue by nuaayxy** [zju3dv/OnePose#4]
Impressive work, when can we try it out the code

**Comment by Aishkrish18** [comment]
Great work! When would the code be released to try out?

**Comment by Witek-** [comment]
Will the code work on Linux only or also on Windows?

**Comment by RiccardoMaistri** [comment]
follow

**Comment by JiamingSuen** [comment]
> Will the code work on Linux only or also on Windows?

The code has been released. It's Linux-only.

**Comment by shalini121906** [comment]
> The code has been released. It's Linux-only.

is there no way to run this project on windows?
