### ISSUE TITLE
ModuleNotFoundError: No module named 'LMCore'

### ISSUE THREAD

**Issue by luffy-yu** [zju3dv/OnePose#40]
It raised an error `ModuleNotFoundError: No module named 'LMCore'` when I ran `python inference_demo.py`.

Does this repo use this [DeepLM](https://github.com/hjwdzh/DeepLM.git)?

**Comment by siatheindochinese** [comment]
Only inference_demo.py uses DeepLM for optical flow tracking. The other script, inference.py runs fine.
