### ISSUE TITLE
Capture app error

### ISSUE THREAD

**Issue by brian2lee** [zju3dv/OnePose#48]
According to the tutorial in the capture app, after adjusting the bounding box, it should scan while I move the cam around in the data capture step. However, the cam froze when I pressed the record button, even stopping the record doesn't help with the frozen cam. The object I'm testing is too big for [OnePoseDatasetCollector](https://github.com/siatheindochinese/OnePoseDatasetCollector) since it only works on handheld-sized size objects.
I'm working on iPad Pro (12.9inch) (3rd gen), ios 15.5, OnePose Capture app ver. 1.4.0

**Comment by brian2lee** [comment]
Welp, it turns out just to be inconsistence.Perhaps I'm unlucky enough to have several frozen screens in a row. At least it works now from time to time.

**Comment by AnukritiSinghh** [comment]
It freezes for me as well, any luck? even my object is bigger in size

**Comment by brian2lee** [comment]
> It freezes for me as well, any luck? even my object is bigger in size

We're discuessing the issue [here](https://github.com/zju3dv/OnePose_Plus_Plus/issues/33) now, Onepose++ but same capture app. Still waiting for further response.
