### ISSUE TITLE
3D特征的问题

### ISSUE THREAD

**Issue by Gatsby23** [zju3dv/OnePose#7]
Dear Professor：
         感谢您在物体位姿估计方面的贡献。在看您论文《OnePose》的时候有一个疑惑：OnePose提出的GAT网络看起来像是3D-2D版本的Super Glue。那在估计的时候，每个3D点当中是否需要保存多个图像当中的2D local descriptor Patch？还是说每个SFM3D点对应一个descriptor用于global retrieval呢？我个人的理解是前者，GAT网络更多的时候是提供一个更为鲁棒的匹配关系，不知道理解是不是正确？

**Comment by JiamingSuen** [comment]
理解是正确的，需要保存多个视角的2D local descriptors.

**Comment by Gatsby23** [comment]
> 理解是正确的，需要保存多个视角的2D local descriptors.

感谢您的回复和及时解答，祝您科研顺利
